application: annotatr
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /styles
  static_dir: styles
- url: /.*
  script: main.py
